<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIbftr3P\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIbftr3P/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIbftr3P.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIbftr3P\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIbftr3P\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ibftr3P',
    'container.build_id' => '3702d11d',
    'container.build_time' => 1644352733,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIbftr3P');
