<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEj5SdHP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEj5SdHP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEj5SdHP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEj5SdHP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEj5SdHP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ej5SdHP',
    'container.build_id' => 'ce38fc2e',
    'container.build_time' => 1644354386,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEj5SdHP');
